services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "9080:9080"
    env_file:
      - .env
    networks:
      - zalando-backend

networks:
  zalando-backend:
    external: true